require_relative '../modules/person'
require_relative '../modules/book'
require_relative '../modules/rental'
require_relative '../modules/student'
require_relative '../modules/teacher'
require_relative '../modules/classroom'
require_relative '../modules/base_decorator'
